title: "test"
url: "https://monsoonmalabar.com/justinechacko"
email: "test@gmail.com"
markdown: kramdown
mobile: "9961555760"
sass:
  sass_dir: _sass
  style: compressed
collections:
  products:
    output: true
defaults:
  - scope:
      type: posts
    values:
      layout: product
  - scope:
      type: products
    values:
      layout: post
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - .jekyll-cache
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
encoding: UTF-8
permalink: /products/:title/
paginate: 4
paginate_path: 'page/:num/'
favicon: "https://i.imgur.com/SF77wJb.png"
paypal: 
analytics: "11111111111111"
adsense: "11111111111111111111111"